package com.echo.vocabplayer;

import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.util.*;

public class MainActivity extends Activity {
    private final ArrayList<AppData.Word> words=new ArrayList<>();
    private android.content.SharedPreferences prefs; private EditText input; private TextView currentEnglish,currentChinese,phase,listTitle,gapLabel;private Button playButton;private WordAdapter adapter;private int currentIndex=0;private boolean playing=false;
    private final BroadcastReceiver stateReceiver=new BroadcastReceiver(){@Override public void onReceive(Context c,Intent i){currentIndex=i.getIntExtra(PlaybackService.EXTRA_INDEX,currentIndex);playing=i.getBooleanExtra(PlaybackService.EXTRA_PLAYING,false);phase.setText(i.getStringExtra(PlaybackService.EXTRA_PHASE));String en=i.getStringExtra(PlaybackService.EXTRA_ENGLISH),cn=i.getStringExtra(PlaybackService.EXTRA_CHINESE);if(en!=null&&!en.isEmpty()){currentEnglish.setText(en);currentChinese.setText(cn);}playButton.setText(playing?"Ⅱ 暂停":"▶ 播放");if(adapter!=null)adapter.notifyDataSetChanged();}};

    @Override public void onCreate(Bundle state){super.onCreate(state);prefs=AppData.prefs(this);words.addAll(AppData.loadWords(this));buildUi();requestNotificationPermission();if(BuildConfig.DEBUG&&getIntent().getBooleanExtra("test_autostart",false)){if(words.isEmpty()){words.add(new AppData.Word("background","后台播放"));AppData.saveWords(this,words);}Intent test=new Intent(this,PlaybackService.class).setAction(PlaybackService.ACTION_START).putExtra(PlaybackService.EXTRA_INDEX,0).putExtra(PlaybackService.EXTRA_TEST_MODE,true);if(Build.VERSION.SDK_INT>=26)startForegroundService(test);else startService(test);}}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);}private TextView text(String s,int sp,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(color);return v;}private Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(14);b.setAllCaps(false);b.setMinHeight(dp(46));return b;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
    private Spinner spinner(String[] labels,int selected){Spinner s=new Spinner(this);ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels);s.setAdapter(a);s.setSelection(selected);return s;}
    private void buildUi(){int navy=Color.rgb(19,32,56),blue=Color.rgb(40,86,216),muted=Color.rgb(104,118,140);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(18),dp(18),dp(18),dp(12));root.setBackgroundColor(Color.rgb(244,247,251));
        TextView title=text("英语单词播放器",23,navy);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);root.addView(title);TextView subtitle=text("锁屏、切后台也能继续播放",14,muted);subtitle.setPadding(0,dp(3),0,dp(12));root.addView(subtitle);
        input=new EditText(this);input.setHint("支持一行多个或每行一个\nbond 情感羁绊  survival 生存");input.setTextSize(16);input.setGravity(Gravity.TOP);input.setPadding(dp(14),dp(12),dp(14),dp(12));input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);input.setBackgroundColor(Color.WHITE);root.addView(input,new LinearLayout.LayoutParams(-1,dp(105)));
        LinearLayout imports=row();imports.setPadding(0,dp(7),0,dp(5));Button paste=button("粘贴剪贴板"),add=button("导入并保存");add.setTextColor(Color.WHITE);add.setBackgroundColor(blue);imports.addView(paste,new LinearLayout.LayoutParams(0,dp(46),1));imports.addView(add,new LinearLayout.LayoutParams(0,dp(46),1));root.addView(imports);paste.setOnClickListener(v->paste());add.setOnClickListener(v->importWords());
        LinearLayout voice=row();voice.addView(text("英语声音",14,navy));String[] accents={"美式发音","英式发音"},genders={"女声","男声"},qualities={"自然优先","离线稳定"};Spinner accent=spinner(accents,prefs.getString("accent","US").equals("UK")?1:0),gender=spinner(genders,prefs.getString("gender","female").equals("male")?1:0),quality=spinner(qualities,prefs.getString("quality","natural").equals("offline")?1:0);voice.addView(accent,new LinearLayout.LayoutParams(0,dp(48),1));voice.addView(gender,new LinearLayout.LayoutParams(0,dp(48),1));voice.addView(quality,new LinearLayout.LayoutParams(0,dp(48),1));root.addView(voice);
        AdapterView.OnItemSelectedListener voiceChanged=new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?>p){}public void onItemSelected(AdapterView<?>p,View v,int pos,long id){prefs.edit().putString("accent",accent.getSelectedItemPosition()==1?"UK":"US").putString("gender",gender.getSelectedItemPosition()==1?"male":"female").putString("quality",quality.getSelectedItemPosition()==1?"offline":"natural").apply();}};accent.setOnItemSelectedListener(voiceChanged);gender.setOnItemSelectedListener(voiceChanged);quality.setOnItemSelectedListener(voiceChanged);
        LinearLayout settings=row();settings.addView(text("英文重复",14,navy));NumberPicker repeat=new NumberPicker(this);repeat.setMinValue(1);repeat.setMaxValue(10);repeat.setValue(prefs.getInt("repeat",3));repeat.setWrapSelectorWheel(false);settings.addView(repeat,new LinearLayout.LayoutParams(dp(70),dp(56)));int gap=prefs.getInt("gap",800);gapLabel=text("停顿 "+String.format(Locale.CHINA,"%.1f秒",gap/1000f),14,navy);settings.addView(gapLabel);SeekBar seek=new SeekBar(this);seek.setMax(10);seek.setProgress(gap/200);settings.addView(seek,new LinearLayout.LayoutParams(0,dp(44),1));root.addView(settings);repeat.setOnValueChangedListener((p,o,n)->prefs.edit().putInt("repeat",n).apply());seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int n,boolean f){gapLabel.setText("停顿 "+String.format(Locale.CHINA,"%.1f秒",n*.2f));}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){prefs.edit().putInt("gap",s.getProgress()*200).apply();}});
        LinearLayout player=new LinearLayout(this);player.setOrientation(LinearLayout.VERTICAL);player.setGravity(Gravity.CENTER);player.setPadding(dp(10),dp(9),dp(10),dp(8));player.setBackgroundColor(Color.WHITE);currentEnglish=text(words.isEmpty()?"等待导入":words.get(0).english,31,navy);currentEnglish.setTypeface(Typeface.DEFAULT,Typeface.BOLD);currentEnglish.setGravity(Gravity.CENTER);player.addView(currentEnglish);currentChinese=text(words.isEmpty()?"粘贴单词后即可播放":words.get(0).chinese,16,muted);currentChinese.setGravity(Gravity.CENTER);player.addView(currentChinese);phase=text("尚未开始",13,blue);phase.setGravity(Gravity.CENTER);player.addView(phase);LinearLayout controls=row();controls.setGravity(Gravity.CENTER);Button restart=button("↺ 从头"),previous=button("◀ 上一词");playButton=button("▶ 播放");Button next=button("下一词 ▶"),stop=button("■ 停止");playButton.setTextColor(Color.WHITE);playButton.setBackgroundColor(blue);for(Button b:new Button[]{restart,previous,playButton,next,stop})controls.addView(b,new LinearLayout.LayoutParams(0,dp(46),1));player.addView(controls);root.addView(player);restart.setOnClickListener(v->startAt(0));previous.setOnClickListener(v->startAt(Math.max(0,currentIndex-1)));playButton.setOnClickListener(v->{if(words.isEmpty()){Toast.makeText(this,"请先导入单词",Toast.LENGTH_SHORT).show();return;}service(playing?PlaybackService.ACTION_TOGGLE:PlaybackService.ACTION_START,currentIndex);});next.setOnClickListener(v->startAt(Math.min(words.size()-1,currentIndex+1)));stop.setOnClickListener(v->service(PlaybackService.ACTION_STOP,currentIndex));
        LinearLayout head=row();head.setPadding(0,dp(8),0,dp(4));listTitle=text("播放列表 · "+words.size()+" 词",18,navy);listTitle.setTypeface(Typeface.DEFAULT,Typeface.BOLD);head.addView(listTitle,new LinearLayout.LayoutParams(0,dp(40),1));Button clear=button("清空");head.addView(clear,new LinearLayout.LayoutParams(dp(80),dp(40)));root.addView(head);clear.setOnClickListener(v->confirmClear());ListView list=new ListView(this);adapter=new WordAdapter(this,words);list.setAdapter(adapter);list.setOnItemClickListener((p,v,pos,id)->startAt(pos));root.addView(list,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
    }
    private void requestNotificationPermission(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},9);}
    private void paste(){android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(cm.hasPrimaryClip()&&cm.getPrimaryClip()!=null)input.setText(cm.getPrimaryClip().getItemAt(0).coerceToText(this));else Toast.makeText(this,"剪贴板里没有文字",Toast.LENGTH_SHORT).show();}
    private void importWords(){ArrayList<AppData.Word> parsed=AppData.parse(input.getText().toString());if(parsed.isEmpty()){Toast.makeText(this,"请按“英文 中文”格式粘贴",Toast.LENGTH_LONG).show();return;}words.addAll(parsed);input.setText("");AppData.saveWords(this,words);adapter.notifyDataSetChanged();listTitle.setText("播放列表 · "+words.size()+" 词");showCurrent();Toast.makeText(this,"已导入 "+parsed.size()+" 个单词",Toast.LENGTH_SHORT).show();}
    private void startAt(int index){if(words.isEmpty()){Toast.makeText(this,"请先导入单词",Toast.LENGTH_SHORT).show();return;}currentIndex=index;service(PlaybackService.ACTION_START,index);}
    private void service(String action,int index){Intent i=new Intent(this,PlaybackService.class).setAction(action).putExtra(PlaybackService.EXTRA_INDEX,index);if(Build.VERSION.SDK_INT>=26&&PlaybackService.ACTION_START.equals(action))startForegroundService(i);else startService(i);}
    private void showCurrent(){if(words.isEmpty()){currentEnglish.setText("等待导入");currentChinese.setText("粘贴单词后即可播放");}else{AppData.Word w=words.get(Math.min(currentIndex,words.size()-1));currentEnglish.setText(w.english);currentChinese.setText(w.chinese);}}
    private void confirmClear(){if(words.isEmpty())return;new AlertDialog.Builder(this).setTitle("清空全部单词？").setMessage("清空后无法恢复").setNegativeButton("取消",null).setPositiveButton("确认清空",(d,w)->{service(PlaybackService.ACTION_STOP,0);words.clear();currentIndex=0;AppData.saveWords(this,words);adapter.notifyDataSetChanged();listTitle.setText("播放列表 · 0 词");showCurrent();phase.setText("尚未开始");}).show();}
    @Override protected void onStart(){super.onStart();IntentFilter f=new IntentFilter(PlaybackService.ACTION_STATE);if(Build.VERSION.SDK_INT>=33)registerReceiver(stateReceiver,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(stateReceiver,f);}
    @Override protected void onStop(){try{unregisterReceiver(stateReceiver);}catch(Exception ignored){}super.onStop();}
    class WordAdapter extends ArrayAdapter<AppData.Word>{WordAdapter(Context c,List<AppData.Word>w){super(c,0,w);}@Override public View getView(int p,View v,ViewGroup parent){LinearLayout line=row();line.setPadding(dp(12),dp(8),dp(12),dp(8));line.setBackgroundColor(p==currentIndex?Color.rgb(234,240,255):Color.WHITE);TextView no=text(String.format(Locale.CHINA,"%02d",p+1),12,Color.GRAY);line.addView(no,new LinearLayout.LayoutParams(dp(42),dp(46)));LinearLayout copy=new LinearLayout(MainActivity.this);copy.setOrientation(LinearLayout.VERTICAL);TextView en=text(getItem(p).english,17,Color.rgb(19,32,56));en.setTypeface(Typeface.DEFAULT,Typeface.BOLD);copy.addView(en);copy.addView(text(getItem(p).chinese,14,Color.rgb(104,118,140)));line.addView(copy,new LinearLayout.LayoutParams(0,dp(50),1));line.addView(text(p==currentIndex&&playing?"Ⅱ":"▶",15,Color.rgb(40,86,216)));return line;}}
}
